# Step 1: Build the Angular application
FROM node:18 AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
# RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the Angular application
RUN npm run build --prod

# Step 2: Create the production image
FROM nginx:stable-alpine

COPY ./config/default.conf /etc/nginx/conf.d/default.conf

# Copy the build output from the previous stage to Nginx's default HTML directory
COPY --from=build /app/dist/ibagent-front/browser /usr/share/nginx/html

# Copy a custom Nginx configuration if needed
# COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
